export const notice = [
  "Generated by addressfield-ts. Do not edit.",
  "",
  "Google libaddressinput metadata",
  "https://github.com/google/libaddressinput",
  "",
  "Creative Commons Attribution 4.0 International (CC BY 4.0)",
  "https://creativecommons.org/licenses/by/4.0/",
].join("\n");

export const header = ["/*!", ...notice.split("\n").map((line) => ` * ${line}`), " */"].join("\n");
