export const dataLicense = "https://creativecommons.org/licenses/by/4.0/";

const attribution = [
  "Generated by addressfield. Do not edit.",
  "",
  "Google libaddressinput metadata",
  "https://github.com/google/libaddressinput",
  "",
  "Creative Commons Attribution 4.0 International (CC BY 4.0)",
  dataLicense,
].join("\n");

export const snapshotNotice = attribution;

export const notice = [
  attribution,
  "",
  "Changes: defaults applied, fields renamed, data split into modules, Effect schemas added.",
].join("\n");

export const header = ["/*!", ...notice.split("\n").map((line) => ` * ${line}`), " */"].join("\n");
